# Copyright (C) Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later

repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        language: system
        entry: make lint
        pass_filenames: false

      - id: format-check
        name: format-check
        language: system
        entry: make format-check
        pass_filenames: false

      - id: license-headers
        name: license-headers
        language: system
        entry: make license
        pass_filenames: false

      - id: security
        name: security
        language: system
        entry: make security
        pass_filenames: false

      - id: typecheck
        name: typecheck
        language: system
        entry: make typecheck
        pass_filenames: false
